apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerToken}}
metadata:
  name: {{ .Values.secretDockerName }}
  namespace: {{ .Values.namespace}}